/*
 * js/lab-ui/strings.js: every visible string of the lab, verbatim from docs/copy.md (sections 2, 9, 10, 11, 12),
 * plus the v2 strings of SPEC.md 9.1 (docking tests, payment), 9.4 (direct links) and 9.7 (methods), listed in
 * notes/lab.md section 4 as candidates for the copy deck.
 * Values in curly braces are filled by the scripts with fill(); nothing here carries a dash, an emoji or an address.
 */

export const S = Object.freeze({
  h1: 'Lab',
  eyebrowTarget: 'TARGET',
  eyebrowLigand: 'LIGAND',
  searchTargets: 'Search targets or PDB id',
  searchLigands: 'Search compounds or plants',
  filterAll: 'All',
  modePair: 'Pair',
  modeTargetMany: 'Target vs many',
  modeLigandMany: 'Ligand vs many',
  selectTop: 'Select top 20',
  chipTarget: 'Target: {target}',
  chipLigand: 'Ligand: {ligand}',
  chooseTarget: 'Choose target',
  chooseLigand: 'Choose ligand',
  sheetTarget: 'Choose a target',
  sheetLigand: 'Choose a ligand',
  done: 'Done',
  toolReset: 'Reset view',
  toolReference: 'Reference ligand',
  toolBox: 'Box',
  toolPocket: 'Pocket',
  toolSurface: 'Surface',
  toolFullscreen: 'Fullscreen',
  legendReceptor: 'receptor',
  legendLigand: 'ligand',
  legendReference: 'reference',
  depthQuick: 'Quick',
  depthQuickNote: 'about 10 s',
  depthStandard: 'Standard',
  depthStandardNote: 'about 30 s',
  depthDeep: 'Deep',
  depthDeepNote: 'about 90 s',
  seed: 'Seed',
  randomise: 'Randomise',
  seedNote: 'Same seed, same pose, on any machine.',
  run: 'Find a pose',
  runEyebrow: 'DOCK',
  runNote: 'Find a pose in your browser, then run the docking test on chain.',
  stop: 'Stop',
  runAgain: 'Run again',
  progress: 'Pose search · {percent}% · best so far {dG} kcal/mol',
  stagePreparing: 'Preparing pocket',
  stageSearch: 'Pose search',
  stageRefining: 'Refining',
  stageFinal: 'Final integer score',
  eyebrowResult: 'RESULT',
  chipBrowser: 'browser estimate',
  chipChain: 'chain score',
  browserSaid: 'Browser said {dG}.',
  bandStrong: 'strong binder',
  bandModerate: 'moderate binder',
  bandWeak: 'weak binder',
  bandNone: 'no binding',
  rowPkd: 'Estimated pKd',
  rowKd: 'Estimated Kd',
  rowLe: 'Ligand efficiency',
  rowHeavy: 'Heavy atoms',
  rowRot: 'Rotatable bonds',
  rowDepth: 'Depth',
  rowMethod: 'Method',
  rowSeed: 'Seed',
  rowSteps: 'Steps',
  rowEvaluations: 'Evaluations',
  rowElapsed: 'Elapsed',
  leUnit: 'kcal/mol per heavy atom',
  kcal: 'kcal/mol',
  eyebrowGeometry: 'GEOMETRY',
  geoBond: 'Bond lengths within tolerance',
  geoPair13: '1-3 distances within tolerance',
  geoClash: 'No internal clashes',
  geoBox: 'All atoms inside the box',
  geoFail: 'This pose fails a geometry check, so the chain would reject it. Run again.',
  eyebrowTerms: 'FIVE TERMS',
  termG1: 'gauss 1',
  termG2: 'gauss 2',
  termRep: 'repulsion',
  termHyd: 'hydrophobic',
  termHb: 'hydrogen bond',
  termsNote: 'Divided by 1 + 0.0585 x rotatable bonds.',
  record: 'Run docking test',
  recordConnect: 'Connect wallet to run the test',
  recordSwitch: 'Switch to Robinhood Chain',
  recordPending: 'Waiting for the chain',
  recordDone: 'Recorded',
  recordApproving: 'Approving $PONCHEM',
  feeLine: 'Docking test fee {price} $PONCHEM or {fee} ETH + gas · paid to the lab treasury',
  payAria: 'How to pay for the docking test',
  payEth: 'Pay {fee} ETH',
  payToken: 'Pay {price} $PONCHEM',
  payTokenSoon: 'after the $PONCHEM launch',
  payEthOff: 'not offered right now',
  payTokenLow: 'Your wallet holds {balance} $PONCHEM. A docking test costs {price}.',
  chainScore: 'Chain score {dG} kcal/mol',
  viewTx: 'View transaction',
  viewTest: 'View docking test',
  testNumber: 'Docking test #{id}',
  share: 'Share this run',
  recordBest: 'Test best',
  recordRow: 'Run test',
  rankedBy: 'Ranked by binding free energy',
  // empty states (copy.md 9)
  emptyTitle: 'No pose yet',
  emptyLine: 'Choose a target and a ligand, then find a pose.',
  noMatchesTitle: 'No matches',
  noMatchesLine: 'Try a shorter name or a PDB id.',
  clearSearch: 'Clear search',
  noGroupTitle: 'Nothing in this group yet',
  noGroupLine: 'Clear the filter to see the whole library.',
  clearFilter: 'Clear filter',
  // toasts (copy.md 10)
  toastRecorded: 'Docking test recorded on chain',
  toastApproveSent: 'Approval sent. Waiting for confirmation.',
  toastApproved: '$PONCHEM approved for the docking test',
  toastViewTx: 'View tx',
  toastChainScore: 'Chain score {dG} kcal/mol',
  toastSent: 'Transaction sent. Waiting for confirmation.',
  toastReverted: 'Transaction reverted. Nothing was recorded.',
  toastLinkCopied: 'Link copied',
  toastStructure: 'Structure loaded from RCSB',
  toastStructureFail: 'Could not load the structure file. Showing the RCSB image.',
  // errors (copy.md 11)
  errChain: 'Could not reach Robinhood Chain. Reads will retry.',
  errRejected: 'The wallet rejected the request.',
  errFee: 'The run fee is {fee} ETH plus gas. The connected wallet does not hold enough ETH.',
  errFailed: 'The transaction failed on chain. Nothing was recorded.',
  errCatalog: 'The catalog could not be loaded. Reload the page.',
  errWorkers: 'Your browser does not support Web Workers, which the docking engine needs.',
  errWebgl: 'WebGL is not available, so the 3D view is off. Scores and records still work.',
  errStopped: 'Docking was stopped. The last best pose is kept.',
  errUnknownTarget: 'Unknown target id.',
  errUnknownLigand: 'Unknown ligand id.',
  // wallet (copy.md 12)
  connectWallet: 'Connect wallet',
  wrongNetworkBand: 'Your wallet is on another network. Ponchem records runs on Robinhood Chain.',
  switchNetwork: 'Switch network',
  // viewer (copy.md 1)
  viewerLoading: 'Loading structure from the Protein Data Bank',
  viewerFallback: '3D view unavailable. Showing the RCSB entry image.',
  // states the copy deck has no line for yet (plain, same voice; listed in notes/lab.md)
  engineMissing: 'The docking engine could not be loaded. Reload the page.',
  labNotLive: 'Recording opens when the lab contract is live on Robinhood Chain.',
  quoteLine: 'Chain dry run {dG} kcal/mol',
  quoteMismatch: 'Chain dry run {dG} kcal/mol, browser said {browser}.',
  quoteRefused: 'The chain refused this pose: {reason}',
  screenProgress: '{i} of {n} · {name}',
  screenEmpty: 'Tick the compounds or targets to screen, then find the poses.',
  poolOf: '{target}',
  rcsbAlt: 'RCSB entry image for {id}',
  rcsbLink: 'RCSB {id}',
  pubchemLink: 'PubChem {id}',
  pairAria: 'Choose the target and the ligand',
  sortAria: 'Sort by binding free energy',
  glossPkd: 'Minus the base ten logarithm of Kd in molar units. Bigger means tighter. A pKd of 6 is one micromolar; 9 is one nanomolar.',
  glossKd: 'Dissociation constant. The concentration at which half the receptor sites are occupied. Smaller means tighter binding. Estimated here from dG = RT ln Kd at 298.15 K.',
  glossLe: 'Binding free energy per heavy atom, as a positive number. It favours small molecules that bind well for their size.',
  // docking methods (SPEC.md 9.7)
  eyebrowMethod: 'METHOD',
  methodTitle: 'Docking method',
  methodChip: 'Method: {name}',
  methodChange: 'Change',
  methodHide: 'Hide',
  methodPreset: 'Preset',
  methodPresets: 'Presets',
  methodMine: 'My methods',
  methodEditor: 'Method JSON',
  methodEditorNote: 'The search that prepares the pose. The chain scoring function is fixed. Fields and bounds are in the docs.',
  methodValid: 'Valid method · {bytes} bytes',
  methodReset: 'Reset to preset',
  methodSave: 'Save as my method',
  methodRemove: 'Remove',
  methodExport: 'Export JSON',
  methodImport: 'Import JSON',
  methodShare: 'Share link',
  methodDocs: 'Docking methods in the docs',
  methodInvalidJson: 'This is not valid JSON: {detail}',
  methodNotObject: 'A method is a JSON object with curly braces.',
  methodTooLong: 'The method JSON is {bytes} bytes. The chain accepts at most 1024.',
  methodNameNeeded: 'Give the method a name in its JSON before saving.',
  methodSaved: 'Method saved as {name}',
  methodRemoved: 'Method removed',
  methodImported: 'Method loaded: {name}',
  methodBadImport: 'That file is not a valid method.',
  methodExported: 'Method JSON downloaded',
  methodBadLink: 'The method in this link is not valid. Standard is selected instead.',
  methodFixFirst: 'Fix the method JSON before finding a pose.',
  methodCustom: 'Edited method',
});

/** fill('Run fee {fee} ETH', { fee: '0.0001' }) -> 'Run fee 0.0001 ETH'. Missing keys stay as written. */
export function fill(template, values = {}) {
  return String(template).replace(/\{(\w+)\}/g, (m, k) => (k in values && values[k] !== undefined && values[k] !== null ? String(values[k]) : m));
}

export const DEPTHS = Object.freeze([
  { key: 'quick', label: S.depthQuick, note: S.depthQuickNote, budgetMs: 10000 },
  { key: 'standard', label: S.depthStandard, note: S.depthStandardNote, budgetMs: 30000 },
  { key: 'deep', label: S.depthDeep, note: S.depthDeepNote, budgetMs: 90000 },
]);

export const KD_UNITS = Object.freeze(['pM', 'nM', 'uM', 'mM', 'M']);
