// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Base} from "./Base.t.sol";
import {PonchemLab} from "../src/PonchemLab.sol";

/// @notice Gas ceilings from SPEC-ENGINE.md 6.1 and the figures for contracts/gas.md. Storage is made cold before
///         each measured call (vm.cool), as a fresh transaction finds it. The figures are for the call alone: a
///         transaction adds 21,000 plus its calldata (one pose word per coordinate, so 96 bytes per atom).
///         Run:  forge test --match-contract GasTest -vv
contract GasTest is Base {
    /// The ceilings SPEC-ENGINE.md 6.1 proposed were 2,500,000 (AQ4 x 1M17) and 6,000,000 (the 64 x 2000 case),
    /// from a model of 80 gas per examined pocket atom and 250 per pair inside the cutoff. The measured costs of the
    /// compiled loop are about 65 per rejected visit, 130 per visit that passes the axis test and 430 per pair
    /// inside the cutoff (profiled opcode by opcode on anvil, see notes/contracts.md), so the ceilings are the
    /// measured numbers plus 15 percent, as that section says to do once the Solidity exists. Both are far below
    /// the chain's 32,000,000 per transaction.
    uint256 internal constant CEIL_REAL = 3_600_000; // AQ4 x 1M17 (real_02): measured 3,121,720
    uint256 internal constant CEIL_WORST = 10_500_000; // TA1 x synthetic 2000-atom pocket: measured 9,166,199

    string internal md;

    function _line(string memory s) internal {
        md = string.concat(md, s, "\n");
    }

    function _used() internal returns (uint256) {
        return vm.lastCallGas().gasTotalUsed;
    }

    function test_gas_ceilings_and_report() public {
        _line("# PonchemLab gas");
        _line("");
        _line("GENERATED by `forge test --match-contract GasTest` (test/Gas.t.sol) with forge 1.7.1, solc 0.8.28, via_ir,");
        _line("optimizer 1,000,000 runs, no Yul inliner, cancun. Execution gas of the call alone, storage cold before");
        _line("each measured call (vm.cool). A transaction adds 21,000 plus calldata: a pose is one word per coordinate, about");
        _line("96 bytes (roughly 1,000 gas) per ligand atom. Robinhood Chain is Arbitrum Nitro: the node adds an L1 data");
        _line("component to eth_estimateGas, usually zero on this chain. Take the limit for a real transaction from");
        _line("eth_estimateGas. The chain allows 32,000,000 gas per transaction.");
        _line("");

        // ------------------------------------------------------------ deployment and registration
        uint256 g0 = gasleft();
        PonchemLab fresh = new PonchemLab(check, owner, treasury, FEE_BPS, RUN_FEE, RUN_PRICE, EPOCH);
        uint256 deployGas = g0 - gasleft();
        vm.prank(owner);
        fresh.setTables(tablesBlob);
        uint256 tablesGas = _used();
        _line("## Deployment");
        _line("");
        _line("| step | gas |");
        _line("|---|---|");
        _line(string.concat("| PonchemLab creation (runtime ", vm.toString(address(fresh).code.length), " bytes) | ", vm.toString(deployGas), " |"));
        _line(string.concat("| setTables (13,010 bytes stored as code) | ", vm.toString(tablesGas), " |"));
        _line("");
        assertLe(address(fresh).code.length, 24_576, "runtime under the EIP-170 limit");

        _line("## Registration (the deploy's bulk)");
        _line("");
        _line("| item | bytes | gas |");
        _line("|---|---|---|");
        string[4] memory files = [
            "real_02_1M17_AQ4_refined.json",
            "real_03_1M17_QUE_docked.json",
            "real_04_1M17_TA1_docked.json",
            "syn_01_methanol_one_pocket_atom.json"
        ];
        string[4] memory ligandNames = ["AQ4 erlotinib (29 atoms)", "QUE quercetin (22 atoms)", "TA1 paclitaxel (62 atoms)", "methanol (2 atoms)"];
        for (uint256 i = 0; i < files.length; i++) {
            Vector memory v = _vector(files[i]);
            if (targetByHash[v.pocketHash] == 0) {
                vm.cool(address(lab));
                vm.prank(owner);
                uint16 t = lab.registerTarget(_pdbIdOf(v.pocket), "Epidermal growth factor receptor kinase domain", 1, v.pocket, v.pocketHash);
                targetByHash[v.pocketHash] = t;
                _line(string.concat("| registerTarget ", _pdbIdOf(v.pocket), " pocket (", vm.toString(uint256(_u16(v.pocket, 4))), " atoms) | ", vm.toString(v.pocket.length), " | ", vm.toString(_used()), " |"));
            }
            if (ligandByHash[v.topologyHash] == 0) {
                vm.cool(address(lab));
                vm.prank(owner);
                uint16 l = lab.registerLigand(string.concat("LIG", vm.toString(i)), ligandNames[i], v.topology, v.topologyHash);
                ligandByHash[v.topologyHash] = l;
                _line(string.concat("| registerLigand ", ligandNames[i], " | ", vm.toString(v.topology.length), " | ", vm.toString(_used()), " |"));
            }
        }
        _line("");
        _line("Rule of thumb for a data blob of B bytes: 32,000 (CREATE) + 200 x B (code deposit) + 16 x B (calldata)");
        _line("+ the structural check (about 200 gas per pocket atom, 150 per topology entry) + about 130,000 of storage");
        _line("and event. contracts/register.sh prints the estimate for the whole registry before sending.");
        _line("");

        // ------------------------------------------------------------ runs
        _line("## Runs (ceilings: measured plus 15 percent, see test/Gas.t.sol; SPEC-ENGINE.md 6.1 proposed 2.5M and 6M)");
        _line("");
        _line("| case | pocket atoms | ligand atoms | quote | submitRun | ceiling |");
        _line("|---|---|---|---|---|---|");
        uint256 worst = 0;
        for (uint256 i = 0; i < 3; i++) {
            Vector memory v = _vector(files[i]);
            uint16 t = targetByHash[v.pocketHash];
            uint16 l = ligandByHash[v.topologyHash];
            vm.cool(address(lab));
            int32 q = lab.quote(t, l, v.pose);
            uint256 quoteGas = _used();
            assertEq(int256(q), v.score);
            vm.cool(address(lab));
            vm.prank(alice);
            lab.submitRun{value: RUN_FEE}(t, l, v.pose);
            uint256 submitGas = _used();
            string memory ceiling = i == 0 ? vm.toString(CEIL_REAL) : "";
            _line(string.concat("| ", v.name, " | 796 | ", vm.toString(v.pose.length / 3), " | ", vm.toString(quoteGas), " | ", vm.toString(submitGas), " | ", ceiling, " |"));
            emit log_named_uint(string.concat(v.name, " quote"), quoteGas);
            emit log_named_uint(string.concat(v.name, " submitRun"), submitGas);
            if (i == 0) assertLe(submitGas, CEIL_REAL, "AQ4 x 1M17 submitRun under 2.5M");
            if (submitGas > worst) worst = submitGas;
        }

        // the worst case of SPEC-ENGINE.md 6.1: a 64-atom-class ligand (TA1, 62 atoms) in a fully buried 2000-atom
        // pocket at protein density (0.05 atoms per cubic angstrom). 2000 atoms at that density fill 40,000 A^3,
        // so the box is (14, 8, 8) A half sizes: a reach cube of 44 x 32 x 32 A = 45,056 A^3 holding the 2000
        // atoms at 0.044 per A^3, uniformly (the TA1 pose of the vector sits inside that box).
        Vector memory ta1 = _vector(files[2]);
        bytes memory synthetic = _syntheticPocket(bytes4("SYNW"), 1400, 800, 800, 2000, 7);
        vm.prank(owner);
        uint16 tw = lab.registerTarget("SYNW", "synthetic 2000-atom pocket", 1, synthetic, keccak256(synthetic));
        uint256 regWorst = _used();
        uint16 lw = ligandByHash[ta1.topologyHash];
        vm.cool(address(lab));
        lab.quote(tw, lw, ta1.pose);
        uint256 quoteWorst = _used();
        vm.cool(address(lab));
        vm.prank(bob);
        lab.submitRun{value: RUN_FEE}(tw, lw, ta1.pose);
        uint256 submitWorst = _used();
        _line(string.concat("| TA1 x synthetic pocket, 2000 atoms uniform in a 44 x 32 x 32 A reach cube | 2000 | 62 | ", vm.toString(quoteWorst), " | ", vm.toString(submitWorst), " | ", vm.toString(CEIL_WORST), " |"));
        _line("");
        _line(string.concat("Registering the synthetic 2000-atom pocket (", vm.toString(synthetic.length), " bytes) cost ", vm.toString(regWorst), " gas."));
        _line("");
        emit log_named_uint("worst case quote", quoteWorst);
        emit log_named_uint("worst case submitRun", submitWorst);
        assertLe(submitWorst, CEIL_WORST, "TA1 x 2000-atom pocket submitRun under 6M");

        // ------------------------------------------------------------ money
        _line("## Money");
        _line("");
        _line("| action | gas |");
        _line("|---|---|");
        uint16 t1 = targetByHash[_vector(files[0]).pocketHash];
        vm.cool(address(lab));
        vm.prank(carol);
        lab.fund{value: 1 ether}(t1);
        _line(string.concat("| fund | ", vm.toString(_used()), " |"));
        _warpEpochs(1);
        vm.deal(alice, alice.balance + 1 wei);
        vm.cool(address(lab));
        lab.settle(t1, 0);
        _line(string.concat("| settle, one epoch with a winner | ", vm.toString(_used()), " |"));
        _fund(carol, t1, 0.5 ether);
        _warpEpochs(3);
        vm.cool(address(lab));
        lab.settle(t1, 3);
        _line(string.concat("| settle, three epochs without a run rolled in one call | ", vm.toString(_used()), " |"));
        RefusingReceiver r = new RefusingReceiver();
        vm.deal(address(r), 1 ether);
        Vector memory v0 = _vector(files[0]);
        vm.prank(address(r));
        lab.submitRun{value: RUN_FEE}(t1, ligandByHash[v0.topologyHash], v0.pose);
        _warpEpochs(1);
        lab.settle(t1, 4);
        r.allow();
        vm.cool(address(lab));
        vm.prank(address(r));
        lab.withdraw();
        _line(string.concat("| withdraw (a refused prize) | ", vm.toString(_used()), " |"));
        _line("");

        // ------------------------------------------------------------ rehearsal figures, when present
        if (vm.exists("out/rehearsal/gas.json")) {
            string memory json = vm.readFile("out/rehearsal/gas.json");
            _line("## Rehearsal on anvil (contracts/register.sh, real receipts)");
            _line("");
            _line(string.concat("Registry `", vm.parseJsonString(json, ".registry"), "`: ", vm.parseJsonString(json, ".targets"), " targets and ", vm.parseJsonString(json, ".ligands"), " ligands."));
            _line("");
            _line("| step | gas used |");
            _line("|---|---|");
            _line(string.concat("| deploy PonchemLab | ", vm.parseJsonString(json, ".deployGas"), " |"));
            _line(string.concat("| setTables | ", vm.parseJsonString(json, ".tablesGas"), " |"));
            _line(string.concat("| registerTarget, total | ", vm.parseJsonString(json, ".targetGas"), " |"));
            _line(string.concat("| registerLigand, total | ", vm.parseJsonString(json, ".ligandGas"), " |"));
            _line(string.concat("| everything (lab + tables + registry) | ", vm.parseJsonString(json, ".totalGas"), " |"));
            _line("");
            if (vm.keyExistsJson(json, ".items")) {
                _line("Per item (receipt gas):");
                _line("");
                _line("| item | bytes | gas |");
                _line("|---|---|---|");
                string[] memory items = vm.parseJsonStringArray(json, ".items");
                for (uint256 i = 0; i < items.length; i++) {
                    _line(items[i]);
                }
                _line("");
            }
        }
        vm.writeFile("gas.md", md);
        _assertSolvent();
    }

    // ---------------------------------------------------------------- synthetic pocket

    /// A pocket with `count` atoms placed pseudo-randomly (uniform) in the whole reach cube of the box, typed at
    /// random, cell-sorted with an offset table: SPEC-ENGINE.md section 5 exactly, as the checker demands.
    function _syntheticPocket(bytes4 id, uint16 hx, uint16 hy, uint16 hz, uint256 count, uint256 seed)
        internal
        pure
        returns (bytes memory out)
    {
        uint256 nx = (2 * uint256(hx) + 1600) / 800 + 1;
        uint256 ny = (2 * uint256(hy) + 1600) / 800 + 1;
        uint256 nz = (2 * uint256(hz) + 1600) / 800 + 1;
        uint256 ncells = nx * ny * nz;
        int256[] memory xs = new int256[](count);
        int256[] memory ys = new int256[](count);
        int256[] memory zs = new int256[](count);
        uint8[] memory ts = new uint8[](count);
        uint256[] memory cell = new uint256[](count);
        uint256[] memory counts = new uint256[](ncells + 1);
        for (uint256 k = 0; k < count; k++) {
            uint256 h = uint256(keccak256(abi.encode(seed, k)));
            xs[k] = int256((h & 0xffff) % (2 * (uint256(hx) + 800) + 1)) - int256(uint256(hx) + 800);
            ys[k] = int256(((h >> 16) & 0xffff) % (2 * (uint256(hy) + 800) + 1)) - int256(uint256(hy) + 800);
            zs[k] = int256(((h >> 32) & 0xffff) % (2 * (uint256(hz) + 800) + 1)) - int256(uint256(hz) + 800);
            ts[k] = uint8((h >> 48) % 16);
            uint256 cx = uint256(xs[k] + int256(uint256(hx)) + 800) / 800;
            uint256 cy = uint256(ys[k] + int256(uint256(hy)) + 800) / 800;
            uint256 cz = uint256(zs[k] + int256(uint256(hz)) + 800) / 800;
            cell[k] = (cx * ny + cy) * nz + cz;
            counts[cell[k] + 1] += 1;
        }
        for (uint256 c = 0; c < ncells; c++) {
            counts[c + 1] += counts[c];
        }
        out = new bytes(28 + 7 * count + 2 * (ncells + 1));
        out[0] = id[0];
        out[1] = id[1];
        out[2] = id[2];
        out[3] = id[3];
        _put16(out, 4, count);
        _put16(out, 6, hx);
        _put16(out, 8, hy);
        _put16(out, 10, hz);
        out[24] = bytes1(uint8(nx));
        out[25] = bytes1(uint8(ny));
        out[26] = bytes1(uint8(nz));
        out[27] = 0x01;
        uint256[] memory fill = new uint256[](ncells);
        for (uint256 k = 0; k < count; k++) {
            uint256 slot = counts[cell[k]] + fill[cell[k]];
            fill[cell[k]] += 1;
            uint256 rec = 28 + 7 * slot;
            _put16(out, rec, uint256(uint16(int16(xs[k]))));
            _put16(out, rec + 2, uint256(uint16(int16(ys[k]))));
            _put16(out, rec + 4, uint256(uint16(int16(zs[k]))));
            out[rec + 6] = bytes1(ts[k]);
        }
        uint256 offs = 28 + 7 * count;
        for (uint256 c = 0; c <= ncells; c++) {
            _put16(out, offs + 2 * c, counts[c]);
        }
    }

    function _put16(bytes memory b, uint256 off, uint256 v) internal pure {
        b[off] = bytes1(uint8(v >> 8));
        b[off + 1] = bytes1(uint8(v));
    }

    function _u16(bytes memory b, uint256 off) internal pure returns (uint256) {
        return (uint256(uint8(b[off])) << 8) | uint256(uint8(b[off + 1]));
    }
}

contract RefusingReceiver {
    bool public open;

    function allow() external {
        open = true;
    }

    receive() external payable {
        require(open, "closed");
    }
}
