#!/usr/bin/env node
/*
 * abi.mjs: regenerate js/abi.js from the forge build of contracts/src/PonchemLab.sol.
 *
 *   node tools/abi.mjs            build, then rewrite js/abi.js when it changed
 *   node tools/abi.mjs --check    build, then exit 1 if js/abi.js is stale (writes nothing)
 *
 * js/abi.js holds `export const LAB_ABI`: the human-readable ABI (functions, events, errors) that js/rpc.js
 * parseFragment / fragment / encodeCall / decodeResult / errorsOf accept, one fragment per line, sorted by kind and
 * name. Errors are included so revert data decodes to a name (BadPose, WrongFee, NotEnded, ...). No dependency:
 * the fragments are formatted here from the JSON ABI in the artifact.
 *
 * submitRun takes five arguments (SPEC.md 9.1 and 9.7): targetId, ligandId, pose, payWithToken, method JSON
 * (may be empty). CHECK_ABI is the ABI of PonchemCheck (pairTerms, the registration checks), for tools and audits.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const C = join(ROOT, 'contracts');
const CHECK = process.argv.includes('--check');
const ABI_JS = join(ROOT, 'js/abi.js');

try {
  execFileSync('forge', ['build'], { cwd: C, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
} catch (e) {
  process.stderr.write(String(e.stdout || '') + String(e.stderr || ''));
  console.error('abi.mjs: forge build failed');
  process.exit(2);
}

function typeOf(p) {
  if (p.type.startsWith('tuple')) {
    const inner = p.components.map(paramText).join(', ');
    return `(${inner})${p.type.slice(5)}`;
  }
  return p.type;
}
function paramText(p, indexedOk = false) {
  const parts = [typeOf(p)];
  if (indexedOk && p.indexed) parts.push('indexed');
  if (p.name) parts.push(p.name);
  return parts.join(' ');
}
function fragmentText(f) {
  if (f.type === 'constructor') return `constructor(${f.inputs.map((p) => paramText(p)).join(', ')})`;
  if (f.type === 'event') return `event ${f.name}(${f.inputs.map((p) => paramText(p, true)).join(', ')})`;
  if (f.type === 'error') return `error ${f.name}(${f.inputs.map((p) => paramText(p)).join(', ')})`;
  if (f.type === 'function') {
    let s = `function ${f.name}(${f.inputs.map((p) => paramText(p)).join(', ')})`;
    if (f.stateMutability && f.stateMutability !== 'nonpayable') s += ` ${f.stateMutability}`;
    if (f.outputs && f.outputs.length) s += ` returns (${f.outputs.map((p) => paramText(p)).join(', ')})`;
    return s;
  }
  return null;
}
function lines(abi) {
  const order = { constructor: 0, function: 1, event: 2, error: 3 };
  // by kind, then name, then the number of inputs (so the three-argument submitRun comes first), then text;
  // plain code-point order, not locale collation
  const cmp = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
  return abi
    .map((f) => ({ type: f.type, name: f.name || '', n: (f.inputs || []).length, text: fragmentText(f) }))
    .filter((f) => f.text)
    .sort((a, b) => order[a.type] - order[b.type] || cmp(a.name.toLowerCase(), b.name.toLowerCase()) || a.n - b.n || cmp(a.text, b.text))
    .map((f) => `  '${f.text.replace(/'/g, "\\'")}',`);
}

const lab = JSON.parse(readFileSync(join(C, 'out/PonchemLab.sol/PonchemLab.json'), 'utf8')).abi;
const check = JSON.parse(readFileSync(join(C, 'out/PonchemCheck.sol/PonchemCheck.json'), 'utf8')).abi;
const labLines = lines(lab);
const checkLines = lines(check);

const out = `/*
 * PonchemLab ABI (human-readable). GENERATED by tools/abi.mjs from the forge build of
 * contracts/src/PonchemLab.sol: do not edit. \`node tools/abi.mjs --check\` fails when this file is stale.
 * Errors are included so revert data decodes to a name (BadPose, WrongFee, NotEnded, NoRuns, ...).
 * submitRun(targetId, ligandId, pose, payWithToken, method): payWithToken false with msg.value == runFee is the ETH path.
 */
export const LAB_ABI = Object.freeze([
${labLines.join('\n')}
]);

/* PonchemCheck: the registration checks and pairTerms, deployed next to the lab (address in contracts/deployments.json). */
export const CHECK_ABI = Object.freeze([
${checkLines.join('\n')}
]);
`;

const have = existsSync(ABI_JS) ? readFileSync(ABI_JS, 'utf8') : '';
if (have === out) {
  console.log('js/abi.js is current');
} else if (CHECK) {
  console.error('js/abi.js is stale: run node tools/abi.mjs');
  process.exit(1);
} else {
  writeFileSync(ABI_JS, out);
  console.log(`wrote js/abi.js (${labLines.length} lab fragments, ${checkLines.length} check fragments)`);
}
